### ISSUE TITLE
Bucket Listing Feature

### ISSUE THREAD

**Issue by cybertron10** [smaranchand/bucky#3]
Thanks for the tool I was always looking for such a tool.

I have one request currently it determines if its vulnerable or not only by uploading a file. But i have manually verified there is a bucket which has listing enabled which was not detected by tool. Is it possible for you to add a feature where we can check which all buckets has read permission.

**Comment by cybertron10** [comment]
Also If it finds a bucket in source code of a domain and if that bucket doesn't exists bucky will show its not vulnerable however attacker can create a new bucket with same name and can report it as subdomain takeover. So It will be nice if bucky has 2 more features.
1) Check whether authenticated read permission is enabled i.e aws s3 ls s3://bucket.s3.amazonaws.com
2) If there is no such bucket then also it should notify us.

**Comment by smaranchand** [comment]
Hi @cybertron10 , Thanks for checking out Bucky, The feature you requested indeed make sense and is already in the pipeline. I am going to add a feature to check for bucket policies as well. For the subdomain takeover issue, Bucky does not perform DNS  checks to find if the site pointed to s3 bucket exists or not but  definitely is an important topic and work on.

Regards,
Smaran
