### ISSUE TITLE
Parse error: syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting '-' or identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) in /Users/cypher/tools/bucky/process.php on line 40

### ISSUE THREAD

**Issue by hassankhan98** [smaranchand/bucky#4]
solution?

![Screen Shot 2020-09-25 at 4 15 06 PM](https://user-images.githubusercontent.com/33081303/94261008-9757d500-ff4a-11ea-9aea-d822d7fb1d11.png)
![Screen Shot 2020-09-25 at 4 15 19 PM](https://user-images.githubusercontent.com/33081303/94261016-9aeb5c00-ff4a-11ea-8adc-ea8e0c1de318.png)

**Comment by smaranchand** [comment]
Hi @hassankhan98 , It seems like your PHP version is less than 7.3, please do update PHP  and  then run Bucky.

Regards,
Smaran
