### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by machinexa2** [smaranchand/bucky#5]
____             _                  __   ___  
 |  _ \           | |                /_ | / _ \ 
 | |_) |_   _  ___| | ___   _   __   _| || | | |
 |  _ <| | | |/ __| |/ / | | |  \ \ / / || | | |
 | |_) | |_| | (__|   <| |_| |   \ V /| || |_| |
 |____/ \__,_|\___|_|\_\__, |    \_/ |_(_)___/ 
                         __/ |                  
                        |___/     
An automatic tool to find misconfigured AWS S3 buckets.  
Developed by : https://twitter.com/smaranchand          

[Sat Sep 26 11:50:19 2020] PHP 7.4.9 Development Server (http://127.0.0.1:13337) started
[Sat Sep 26 11:52:52 2020] 127.0.0.1:55550 Accepted
[Sat Sep 26 11:52:53 2020] 127.0.0.1:55550 [200]: GET /
[Sat Sep 26 11:52:53 2020] 127.0.0.1:55550 Closing
[Sat Sep 26 11:52:53 2020] 127.0.0.1:55552 Accepted
[Sat Sep 26 11:52:53 2020] 127.0.0.1:55552 [200]: GET /bucky.gif
[Sat Sep 26 11:52:53 2020] 127.0.0.1:55552 Closing
[Sat Sep 26 11:52:53 2020] 127.0.0.1:55554 Accepted
[Sat Sep 26 11:52:53 2020] 127.0.0.1:55554 [404]: GET /favicon.ico - No such file or directory
[Sat Sep 26 11:52:53 2020] 127.0.0.1:55554 Closing
[Sat Sep 26 11:52:57 2020] 127.0.0.1:55556 Accepted
[Sat Sep 26 11:52:57 2020] PHP Fatal error:  Uncaught Error: Class 'SQLite3' not found in /root/MachineYadav/Softwares/Bucky/all_buckets.php:65
Stack trace:
#0 {main}
  thrown in /root/MachineYadav/Softwares/Bucky/all_buckets.php on line 65
[Sat Sep 26 11:52:57 2020] 127.0.0.1:55556 [500]: GET /all_buckets.php - Uncaught Error: Class 'SQLite3' not found in /root/MachineYadav/Softwares/Bucky/all_buckets.php:65                                                                                                                             
Stack trace:                                                                                                                                        
#0 {main}                                                                                                                                           
  thrown in /root/MachineYadav/Softwares/Bucky/all_buckets.php on line 65                                                                           
[Sat Sep 26 11:52:57 2020] 127.0.0.1:55556 Closing
[Sat Sep 26 11:54:02 2020] 127.0.0.1:55598 Accepted
[Sat Sep 26 11:54:02 2020] PHP Fatal error:  Uncaught Error: Class 'SQLite3' not found in /root/MachineYadav/Softwares/Bucky/all_buckets.php:65
Stack trace:
#0 {main}
  thrown in /root/MachineYadav/Softwares/Bucky/all_buckets.php on line 65
[Sat Sep 26 11:54:02 2020] 127.0.0.1:55598 [500]: GET /all_buckets.php - Uncaught Error: Class 'SQLite3' not found in /root/MachineYadav/Softwares/Bucky/all_buckets.php:65                                                                                                                             
Stack trace:                                                                                                                                        
#0 {main}                                                                                                                                           
  thrown in /root/MachineYadav/Softwares/Bucky/all_buckets.php on line 65                                                                           
[Sat Sep 26 11:54:02 2020] 127.0.0.1:55598 Closing

I added firefox-extension and bash run.sh
However i am getting error.

**Comment by machinexa2** [comment]
Even after visiting the url: https://cdn-dummy.s3.amazonaws.com/text.text
i am getting empty buckets

**Comment by machinexa2** [comment]
I added extension, keys in config.inc.php and loaded addons/ using about:debugging

**Comment by machinexa2** [comment]
![image](https://user-images.githubusercontent.com/60662297/94331868-d429d780-ffef-11ea-9362-dd2e0651387c.png)

**Comment by machinexa2** [comment]
http://127.0.0.1:13337/all_buckets.php
![image](https://user-images.githubusercontent.com/60662297/94331880-e0ae3000-ffef-11ea-84cd-53086544d37d.png)

**Comment by machinexa2** [comment]
my php version is 7.4

**Comment by smaranchand** [comment]
Hi @machinexa2 All seems perfect except SQLite3 installation , please do install SQLite3 by using `apt install php7.4-sqlite3` or `apt install sqlite3` and then visit the sites to discover the S3 buckets. For example you can visit https://github.com  or https://console.aws.amazon.com/  and return back to dashboard to see the results. 

Regards,
Smaran

**Comment by machinexa2** [comment]
@smaranchand root@kali-linux:~# apt install sqlite3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sqlite3 is already the newest version (3.33.0-1).
The following packages were automatically installed and are no longer required:
  libpython-all-dev libusrsctp1 linux-image-5.7.0-kali3-amd64 python-all python-all-dev
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@kali-linux:~#

**Comment by machinexa2** [comment]
```
root@kali-linux:~# apt install sqlite3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sqlite3 is already the newest version (3.33.0-1).
The following packages were automatically installed and are no longer required:
  libpython-all-dev libusrsctp1 linux-image-5.7.0-kali3-amd64 python-all python-all-dev
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@kali-linux:~# 
```

**Comment by machinexa2** [comment]
i already had sqlite3 installed

**Comment by machinexa2** [comment]
but i didnt have sqlite installed let me install and try

**Comment by machinexa2** [comment]
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libpython-all-dev libusrsctp1 linux-image-5.7.0-kali3-amd64 python-all python-all-dev
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  libsqlite0
Suggested packages:
  sqlite-doc
The following NEW packages will be installed:
  libsqlite0 sqlite
```

**Comment by machinexa2** [comment]
still same error
```
Stack trace:
#0 {main}
  thrown in /root/MachineYadav/Softwares/Bucky/all_buckets.php on line 65
[Sat Sep 26 21:47:48 2020] 127.0.0.1:47414 [500]: GET /all_buckets.php - Uncaught Error: Class 'SQLite3' not found in /root/MachineYadav/Softwares/Bucky/all_buckets.php:65                                                                                                                             
Stack trace:                                                                                                                                        
#0 {main}                                                                                                                                           
  thrown in /root/MachineYadav/Softwares/Bucky/all_buckets.php on line 65                                                                           
[Sat Sep 26 21:47:48 2020] 127.0.0.1:47414 Closing

```

**Comment by machinexa2** [comment]
@smaranchand even if i installed sqlite1 / `apt install sqlite` it didnt work

**Comment by machinexa2** [comment]
oh i didnt have installed php7.4-sqlite

**Comment by machinexa2** [comment]
ok lets see if it works now

**Comment by machinexa2** [comment]
it works :+1: :smile:
