### ISSUE TITLE
bucky not running

### ISSUE THREAD

**Issue by maddy45** [smaranchand/bucky#6]
**Describe the bug**
I am trying to run bucky in ubuntu 20, WSL in win 10, not able to check buckets manually and using addon, here I am pasting my error response of the tool.

[Tue Sep 29 17:10:29 2020] PHP 7.4.3 Development Server (http://127.0.0.1:13337) started
[Tue Sep 29 17:10:43 2020] 127.0.0.1:41274 Accepted
[Tue Sep 29 17:10:47 2020] 127.0.0.1:41274 [200]: GET /manual_check.php
[Tue Sep 29 17:10:47 2020] 127.0.0.1:41274 Closing
[Tue Sep 29 17:12:15 2020] 127.0.0.1:41276 Accepted
[Tue Sep 29 17:12:20 2020] 127.0.0.1:41276 Closed without sending a request; it was probably just an unused speculative preconnection
[Tue Sep 29 17:12:20 2020] 127.0.0.1:41276 Closing
[Tue Sep 29 17:12:51 2020] 127.0.0.1:41278 Accepted
[Tue Sep 29 17:12:51 2020] 127.0.0.1:41278 [500]: POST /process.php - Uncaught Error: Call to undefined function curl_init() in /home/mad/tools/bucky/lib/requestcore/requestcore.class.php:620
Stack trace:
#0 /home/mad/tools/bucky/lib/requestcore/requestcore.class.php(843): RequestCore->prep_request()
#1 /home/mad/tools/bucky/services/s3.class.php(954): RequestCore->send_request()
#2 /home/mad/tools/bucky/services/s3.class.php(1465): AmazonS3->authenticate()
#3 /home/mad/tools/bucky/process.php(81): AmazonS3->create_object()
#4 {main}
  thrown in /home/mad/tools/bucky/lib/requestcore/requestcore.class.php on line 620

**Comment by smaranchand** [comment]
hi @maddy45 Its seems like CURL extension is not installed in your system, please install CURL using ``` sudo apt-get install php7.2-curl``` and do let me know.

Regards,
Smaran
