### ISSUE TITLE
Bucky Is not giving me any kind of output I tried multiple websites

### ISSUE THREAD

**Issue by ShashankMudg** [smaranchand/bucky#8]
It is showing me this 

POST /process.php - Uncaught Error: Call to undefined function curl_init() in /root/scripts/bucky/lib/requestcore/requestcore.class.php:620                                                                                                                                               
Stack trace:                                                                                                                                                          
#0 /root/scripts/bucky/lib/requestcore/requestcore.class.php(843): RequestCore->prep_request()                                                                        
#1 /root/scripts/bucky/services/s3.class.php(954): RequestCore->send_request()                                                                                        
#2 /root/scripts/bucky/services/s3.class.php(1465): AmazonS3->authenticate()                                                                                          
#3 /root/scripts/bucky/process.php(81): AmazonS3->create_object()                                                                                                     
#4 {main}                                                                                                                                                             
  thrown in /root/scripts/bucky/lib/requestcore/requestcore.class.php on line 620

![buckyshell](https://user-images.githubusercontent.com/51877605/97805952-25785700-1c7f-11eb-9a3a-422cc6f6d041.png)
![buckyout](https://user-images.githubusercontent.com/51877605/97805963-3fb23500-1c7f-11eb-9db4-8896d1a1f465.png)

**Desktop (please complete the following information):**
 - OS: Kali linux
 - Browser: firefox 
- Version: 68.7.0esr 
**Additional context**

**Comment by smaranchand** [comment]
Hi @shashank31github , 

Sorry for the late reply, it seems like php-curl isn't installed in your system, you can do it by ```sudo apt-get install php7.2-curl``` 

Regards,
Smaran
