### ISSUE TITLE
SQLite3 not found error

### ISSUE THREAD

**Issue by Pratham0x01** [smaranchand/bucky#9]
After opening the link in the browser as suggested in the demo video the error thrown is 
" Uncaught Error: Class 'SQLite3' not found in /home/pratham0x01/tools/bucky/all_buckets.php:65".
The result of this is, After my visit to a website the bucket information is not reflecting in bucky dashboard page.

**Screenshots**
![Screenshot from 2020-12-05 20-17-54](https://user-images.githubusercontent.com/26475938/101246088-06199180-3737-11eb-9412-2443aedc9880.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Browser [e.g. chrome]

**Comment by smaranchand** [comment]
Hi @Pratham0x01  Thanks for trying out Bucky, and sorry I couldn't reply to you in time. By analyzing the error it seems like you have not installed sqlite3, which is a database system used by Bucky for storing data, you can do it by using ```apt install php7.4-sqlite3```  
Please do let me know in case of any issues.

Regards,
Smaran
